<div id="customer-app">
    <button id="new-button" class="btn btn-primary">New</button>
    <ul id="customer-list">

    </ul>

    <li id="item-template hide">
        <%= nameFirst%> <%= nameLast%> - <%= email%> <a class="edit btn btn-success" href="#">Edit</a>
    </li>




    <div id="customer-details-modal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <?php echo $this->form($form); ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>